name: CI for Develop Branch

# trigger
on:
  push:
    branches:
      - develop

# jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
